version: "2.1"

volumes:
  bookstack:
  mariadb:

services:
  # https://hub.docker.com/r/linuxserver/bookstack/
  bookstack:
    build: bookstack
    environment:
      DB_HOST: mariadb
      DB_DATABASE: bookstack
      DB_USER: bookstack
      DB_PASS: bookstack
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_SERVERS: redis:6379:0
      APP_URL: http://bookstack.local
      BALENA_HOSTNAME: bookstack
    ports:
      - 80:80/tcp
    volumes:
      - bookstack:/config
    depends_on:
      - mariadb
      - redis
    labels:
      io.balena.features.supervisor-api: 1

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.0.9-alpine

  # https://hub.docker.com/r/yobasystems/alpine-mariadb
  mariadb:
    build: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: bookstack
