version: "2.1"

volumes:
  bookstack:
  mariadb:

services:
  # https://hub.docker.com/r/linuxserver/bookstack/
  bookstack:
    build: app
    environment:
      DB_HOST: mariadb
      DB_DATABASE: bookstack
      DB_USER: bookstack
      DB_PASS: bookstack
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_SERVERS: redis:6379:0
      APP_URL: http://bookstack.local
    ports:
      - 80:80/tcp
    volumes:
      - bookstack:/config
    depends_on:
      - mariadb
      - redis
    labels:
      io.balena.features.supervisor-api: 1

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.0.9-alpine

  # https://hub.docker.com/r/yobasystems/alpine-mariadb
  mariadb:
    image: yobasystems/alpine-mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: bookstack
      MYSQL_ROOT_PASSWORD: balena
    # Repurpose the healthcheck cmd by having it export our database on a schedule.
    # Run the backup every 1 hour to a file called hourly-backup.sql.
    # How to restore: <https://mariadb.com/kb/en/mysqldump/#restoring>
    healthcheck:
      test: mysqldump -uroot -p$MYSQL_ROOT_PASSWORD --all-databases --result-file=/var/lib/mysql/hourly-backup.sql || exit 0
      interval: 1h
      timeout: 30s
      retries: 3
