version: "2.1"

volumes:
  bookstack:
  exported:
  mariadb:
  duplicati:

services:
  # https://hub.docker.com/r/linuxserver/bookstack/
  bookstack:
    build: bookstack
    environment:
      DB_HOST: mariadb
      DB_DATABASE: bookstack
      DB_USER: bookstack
      DB_PASS: bookstack
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_SERVERS: redis:6379:0
    ports:
      - 80:80/tcp
    volumes:
      - bookstack:/config
    depends_on:
      - mariadb
      - redis
  
  # https://gist.github.com/ssddanbrown/45acb913a7b873240b2d89781e74a7a4
  export-books:
    build: export-books
    volumes:
      - exported:/exported
    depends_on:
      - bookstack

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.0.9-alpine

  # https://hub.docker.com/_/mariadb/
  mariadb:
    build: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: bookstack

  # https://hub.docker.com/_/mariadb/
  mysqldump:
    build: mariadb
    command: "/sqldump.sh"
    environment:
      MYSQL_DATABASE: bookstack
    volumes:
      - mariadb:/var/lib/mysql
    depends_on:
      - mariadb

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati:v2.0.5.1-2.0.5.1_beta_2020-01-18-ls83
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - bookstack:/source/bookstack
      - mariadb:/source/mariadb
      - exported:/source/exported
